{% set name = "pylsqpack" %}
{% set version = "0.3.17" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylsqpack-{{ version }}.tar.gz
  sha256: 2f20778db956dc7e4b1a8a79722d57a4650c45997fb65c1352cbf85eb7aa3ce2

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - pylsqpack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiortc/pylsqpack
  summary: Python wrapper for the ls-qpack QPACK library
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - vendor/ls-qpack/LICENSE

extra:
  recipe-maintainers:
    - jonashaag
