{% set name = "pylsqpack" %}
{% set version = "0.3.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylsqpack-{{ version }}.tar.gz
  sha256: 45ae55e721877505f4d5ccd49591d69353f2a548a8673dfafb251d385b3c097f

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - pylsqpack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiortc/pylsqpack
  summary: Python wrapper for the ls-qpack QPACK library
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - vendor/ls-qpack/LICENSE

extra:
  recipe-maintainers:
    - jonashaag
